[package]
name = "mac-notification-sys"
version = "0.2.0"
authors = ["Felix DÃ¶ring <development@felixdoering.com>"]
description = "Thin wrapper around macOS Notifications."

homepage = "https://github.com/h4llow3En/mac-notification-sys"
repository = "https://github.com/h4llow3En/mac-notification-sys"
documentation = "https://h4llow3en.github.io/mac-notification-sys/mac_notification_sys/"

license = "MIT"
keywords = ["notification", "masOS", "osx", "notify"]
readme = "README.md"

include = ["Cargo.toml", "build.rs", "objc/*", "src/*.rs", "tests/*.rs"]

build = "build.rs"

[dependencies]
objc-foundation = "0.1.1"
chrono = "0.4.0"
failure = "0.1.1"
dirs = "1.0"

[build-dependencies]
cc = "1.0.17"
