[package]
name = "mac-notification-sys"
version = "0.3.1"
authors = ["Felix DÃ¶ring <development@felixdoering.com>", "Hendrik Sollich <hendrik@hoodie.de>"]
description = "Thin wrapper around macOS Notifications."
edition = "2018"
rust-version = "1.56"

homepage = "https://github.com/h4llow3En/mac-notification-sys"
repository = "https://github.com/h4llow3En/mac-notification-sys"
documentation = "https://h4llow3en.github.io/mac-notification-sys/mac_notification_sys/"

license = "MIT"
keywords = ["notification", "masOS", "osx", "notify"]
readme = "README.md"

include = ["Cargo.toml", "build.rs", "objc/*", "src/*.rs", "tests/*.rs"]

build = "build.rs"

[dependencies]
objc-foundation = "0.1.1"
objc_id = "0.1.1"
time = "0.3"
dirs-next = "2.0.0"

[build-dependencies]
cc = "1.0.17"
